# Generated by Django 4.2 on 2025-04-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news_app.news'),
        ),
    ]
